services:
  - type: web
    name: eco-footprint-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIMATIQ_API_KEY
        sync: false
