// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqvxekfividzcohphwqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdnhla2ZpdmlkemNvaHBod3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTY1NDYsImV4cCI6MjA2MjczMjU0Nn0.n2MBghl3RiifE8RSMoQdWgyiK-90PYvt3hb1Km8hOss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);